### ISSUE TITLE
WobbleX_WS8_PrintedAdapter.step is corrupted.

### ISSUE THREAD

**Issue by H20Slicer** [MirageC79/Interfaces-for-WobbleX-integration#10]
I've attempted to import the step file into both Solidworks and Fusion 360 and both fail to read the model.
![image](https://user-images.githubusercontent.com/62770014/229960796-523e6cef-cbaf-4eb2-8de4-475e23ec16b7.png)

**Comment by H20Slicer** [comment]
Turns out I was saving the file in the wrong manner.

**Comment by MirageC79** [comment]
Yes, I was just about to answer you back.  I struggle with GitHub for single file download too.  I don't know how I could make this easier.
