### ISSUE TITLE
Print files of WobbleX #2

### ISSUE THREAD

**Issue by pasha4ur** [MirageC79/Interfaces-for-WobbleX-integration#13]
Hello

You closed topic and didn't answer:  https://github.com/MirageC79/Interfaces-for-WobbleX-integration/issues/2

Will you give us files for selfprinting (WS8 and WS12 too) or  you are so greedy that you will sell remade free solution?

3d print community wants to know how low you can fell.

**Comment by pasha4ur** [comment]
Source of idea for your parts as you said: https://www.thingiverse.com/thing:4781610

HevORT Wobble Rings for FSU1204 ball screws by[EvoMotors](https://www.thingiverse.com/EvoMotors)is licensed under the[Creative Commons - Attribution - **Non-Commercial**](https://creativecommons.org/licenses/by-nc/4.0/) license. https://creativecommons.org/licenses/by-nc/4.0/

**Comment by pasha4ur** [comment]
Print version https://www.printables.com/model/439423-wobble-biscuit/comments

Greedy Mirage will not share

**Comment by MirageC79** [comment]
Yeah... I am soooo greedy!  all of the ideas me and my team have put forward over the years... Yet this simple side project is what you use to label me as greedy...

Can't see the forest for the trees...
