### ISSUE TITLE
Mockup .step files unreadable in Fusion360

### ISSUE THREAD

**Issue by cribblekris** [MirageC79/Interfaces-for-WobbleX-integration#24]
I'm unable to open these files. I would like to use them for a custom build.

**Comment by leecuk** [comment]
Try cloning the repo or downloading the raw file rather than trying to save the link to the step file.

**Comment by cribblekris** [comment]
Thanks that worked

**Comment by cribblekris** [comment]
Thanks that worked

**Comment by Garryb123** [comment]
Thank you! That worked.
