### ISSUE TITLE
Ratrig BOM

### ISSUE THREAD

**Issue by kevinkga** [MirageC79/Interfaces-for-WobbleX-integration#26]
The current link to the ws8 variant of wobblex points to a kit that has 8 dowel pins in total. All of these are used by the WobbleX itself.

However, it'd seem like the lower disc adaptor needs additional pins. Could we please have the BOM updated to account for these additional pins? What specs are they and where can they be bought (in the UK)?

**Comment by ZeyHex** [comment]
There are 8 pins in addition to those already installed in WobbleX.

**Comment by kevinkga** [comment]
Thanks for the clarification! that makes perfect sense. I just wish Mellow would clarify that in the product description/BOM
