### ISSUE TITLE
Creality 3 / PRO

### ISSUE THREAD

**Issue by Almazick** [MirageC79/Interfaces-for-WobbleX-integration#5]
I'm just a little bit confused.  The model in Creality folder shows 2 parts but missing dimensions for pins and ball sizes.  Personally I'd like to buy the whole kit from https://www.aliexpress.us/item/3256804040834604.html
Even if buy your part it won't work because it's missing the other 2 parts.  I can't make these parts because they are missing build information for pins and balls.  Can you elaborate?

**Comment by MirageC79** [comment]
Hi, The WS8 kit comes with 
- One cross pre assembled with qty4 magnets and qty8 3mm pins 
- Qty 4 Ball bearings of 4mm diameter (I have asked Mellow to add two spares)
- Qty 8 additional 3mm diameter X 8mm long pins to be inserted in the printed parts.

The BOM and details for Ender3 has been updated.

I am closing the ticket with this comment, but do not hesitate to let me know if you need more info.
Regards,
