### ISSUE TITLE
Ender3 issues

### ISSUE THREAD

**Issue by leecuk** [MirageC79/Interfaces-for-WobbleX-integration#7]
Hi, great project,

I believe the WobbleX_TR8_Adapter Body might have a small issue.

Design has a 16mm screw mount PCD, the brass nut actually has an 18mm PCD.

Additionally, the existing nut has threaded holes which would require the screw to be from the top, how much clearance on top is required for the WobbleX movement?

Thanks
Lee

<img width="303" alt="d" src="https://user-images.githubusercontent.com/18126527/229292317-d71d74ce-9363-443f-b27e-2784f18b7fc0.png">

**Comment by MirageC79** [comment]
Oh!  sweet! thanks for the update.  I'll revise the design.

**Comment by julian-margara** [comment]
Hi there,

I modified the PCD to 18mm, I'm not a design expert by any means but maybe my change will help to someone else.

I can't upload the file here but here is the OnShape document from where it's possible to export to any format (stl, step, etc).
https://cad.onshape.com/documents/cc9a77c7250780a055705ba5/w/e54ded23702a3f2bf6409cc8/e/cab1ab567e6af58cdebe1ea9?renderMode=0&uiState=64395ef437952e7f6c7ce812

I'll update my feedback here after testing it (waiting my kit from AliExpress!)

Best

**Comment by leecuk** [comment]
Might need a recess for screw to sit in, the nut is tapped and requires the screw to be from above. I’m not sure how much clearance is needed. Also waiting on my kit.

**Comment by julian-margara** [comment]
@leecuk why don't put the screw from below? (honest question)

Look how it looks with the 18mm PCD and using the screws (stock ones) from below:
![PXL_20230414_163126041](https://user-images.githubusercontent.com/8016027/232104478-b3fc9df2-c863-4e87-9444-82b57a8367e0.jpg)
![PXL_20230414_163155496](https://user-images.githubusercontent.com/8016027/232104519-8aa7f81d-3760-4021-8871-da6a6bac032a.jpg)
![PXL_20230414_163118744 MP](https://user-images.githubusercontent.com/8016027/232104524-34560a5b-f587-4060-aa91-f171e860d1c3.jpg)

**Comment by leecuk** [comment]
Unless you drill out the thread in the nut, once the screw hits the bottom of the nut thread, it won’t pull the two pieces together. I believe it is sometimes called screw bridging or jacking. 

I also can’t say I’m a fan of tapping directly into the plastic, but a possibly a threaded insert might make it better.

**Comment by leecuk** [comment]
@julian-margara
My WobbleX arrived today, I'm not sure if I ended up purchasing a clone, but the included rollers were a little shorter than expected. 

The bottom mount fouls the carriage bracket on the ender3, so I've chopped the corner off.

<img width="483" alt="image2" src="https://user-images.githubusercontent.com/18126527/235321955-09a33d37-cda4-40d5-9a4e-d63460cc4f2c.png">

<img width="427" alt="image1" src="https://user-images.githubusercontent.com/18126527/235321953-adcffc23-5573-41da-b061-0df9a3e05d76.png">

I used threaded inserts for the top adapter.

I've uploaded step files to https://github.com/leecuk/WobbleX-Ender3 if anyone wants them.

**Comment by nevermor113** [comment]
> Chào bạn,
> 
> Tôi đã sửa đổi PCD thành 18mm, tôi không phải là chuyên gia thiết kế nhưng có lẽ sự thay đổi của tôi sẽ giúp ích cho người khác.
> 
> Tôi không thể tải tệp lên đây nhưng đây là tài liệu OnShape từ đó có thể xuất sang bất kỳ định dạng nào (stl, step, v.v.). https://cad.onshape.com/documents/cc9a77c7250780a055705ba5/w/e54ded23702a3f2bf6409cc8/e/cab1ab567e6af58cdebe1ea9
> 
> Tôi sẽ cập nhật phản hồi của mình tại đây sau khi thử nghiệm (chờ bộ kit của tôi từ AliExpress!)
> 
> Tốt nhất

can you send me the middle part file? I didn't see them post it online

**Comment by ESOCHI** [comment]
> Oh! sweet! thanks for the update. I'll revise the design.

Just fyi, mine was still 16 when I downloaded the Ender3 files.

**Comment by ESOCHI** [comment]
> @julian-margara My WobbleX arrived today, I'm not sure if I ended up purchasing a clone, but the included rollers were a little shorter than expected.
> 
> The bottom mount fouls the carriage bracket on the ender3, so I've chopped the corner off.
> 
> <img alt="image2" width="483" src="https://user-images.githubusercontent.com/18126527/235321955-09a33d37-cda4-40d5-9a4e-d63460cc4f2c.png">
> 
> <img alt="image1" width="427" src="https://user-images.githubusercontent.com/18126527/235321953-adcffc23-5573-41da-b061-0df9a3e05d76.png">
> 
> I used threaded inserts for the top adapter.
> 
> I've uploaded step files to https://github.com/leecuk/WobbleX-Ender3 if anyone wants them.

How did you get the extruder stepper back on? That 3rd bolt area for the top plate conflicts with one of the 4 mounting points for the stepper.  I think my hardware is the same as yours but I may be wrong. I did the ender-extender kit years ago but I don't think my bracketry changed. (I may be wrong)

I flipped the top mount 180 and that got it closer to fitting but still off by 1cm~

Since I need to offset the stepper by 1cm, I've cut the entire middle circle section out of the bracket, and I'm re-drilling the 2 holes that still fit on said bracket. I'll then need to extend the bracket to add the other 2 holes which I may do by drilling an aluminum business card out to fit the stepper, then bolt that to the bracket or something.

[Here's a google album with some pics of everything.](https://photos.app.goo.gl/tgNgBSQznW8CyqgE9)

**Comment by leecuk** [comment]
I’ve completely shifted the extruder. I’m running a e3d titan extruder, so made an adapter plate that bolts into the original mount. You can see it in my photos.

**Comment by leecuk** [comment]
So, it's been just under a year since I installed the WobbleX on the ender, got to say the results are fantastic, so thanks to everyone that put it together.

In terms of the ender3 v2 files, the ones on this repo still aren't currently compatible, but I've got them over at https://github.com/leecuk/WobbleX-Ender3 if anyone want them.
